### ISSUE TITLE
Add pages with `React Router`

### ISSUE THREAD

**Issue by pbrdmn** [dustykeyboard/siligong-hacktoberfest-2019#6]
* Add `React Router` dependency
* Use the [HashRouter](https://reacttraining.com/react-router/web/api/HashRouter) as the site is served from static hosting (Github Pages)

**Comment by aruniverse** [comment]
I can attack this if youd like

**Comment by pbrdmn** [comment]
Not at this time thanks.
Will be hosting a Hacktoberfest event later in the week and using this repo as a demonstration.
