### ISSUE TITLE
Add a *Sponsors* section

### ISSUE THREAD

**Issue by pbrdmn** [dustykeyboard/siligong-hacktoberfest-2019#8]
Add a section to display, name, logo and link for sponsors 

* Event Hosted by: Accelo

**Comment by tomkennedycode** [comment]
Hi, i can do this

**Comment by pbrdmn** [comment]
Hi Tom, glad you'd be happy to help, but I'm not quite ready for this yet.

**Comment by tomkennedycode** [comment]
Are there any issues that you would like me to do?

**Comment by pbrdmn** [comment]
Not at this time thanks Tom.
Will be hosting a Hacktoberfest event later in the week and using this repo as a demonstration.
