### ISSUE TITLE
Add a *dark mode/light mode* toggle

### ISSUE THREAD

**Issue by pbrdmn** [dustykeyboard/siligong-hacktoberfest-2019#9]
Add a toggle to switch between light mode and dark mode

**Comment by nitinv-gh** [comment]
I can take this up 🙂

**Comment by pbrdmn** [comment]
Not at this time thanks.
Will be hosting a Hacktoberfest event later in the week and using this repo as a demonstration.

**Comment by pbrdmn** [comment]
Closed with #14
